#pragma config(Motor,  port2,           mobileGoal,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           backRight,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Sign is a ternary statment
#define sign(x) ((x) < 0 ? -1 : 1)
// toggle -- 1 -> (1-1)=0;  0 -> (1-0)=1
#define toggle(x) (1 - (x))
#define min(x,y) ((x) > (y) ? (y) : (x))
#define max(x,y) ((x) > (y) ? (x) : (y))
#define resetButton (vexRT[Btn7Ch2int lastElevator = 0;
int activeElevator = 1, stopElevator = 0;
int elevatorBottom = 0;
int elevatorTop = 1;
int lastElevator = 1;
int elevatorDone = 0;
void mobileGoalChange(int degs) // Lift Up using encoders
{
	if(stopElevator == 0)
	{
		if(degs == elevatorTop && lastElevator == elevatorBottom)
		{
			elevatorDone = 0;
			activeElevator = time10[T1] + 100;
			motor[mobileGoal] = 127;
			stopElevator = 1;
		}
		else if(degs == elevatorBottom && lastElevator == elevatorTop)
		{
			elevatorDone = 0;
			activeElevator = time10[T1] + 100;
			motor[mobileGoal] = -127;
			stopElevator = 1;
		}
	}
	else
	{
		if(time10[T1] > activeElevator)
		{
			motor[mobileGoal] = 0;
			elevatorDone = 1;
			stopElevator = 0;
		}
	}
	lastElevator = degs;
}
task main()
{
	int mgGoal = 1;
	int left = 0, right = 0, reverseDrive = 0;
	while(1)
	{
		// Drive Code
		left  = abs(vexRT[Ch3]);
		right  = abs(vexRT[Ch2]);
		left = (5*left*left + 305*left + 3624)/1000;
		right = (5*right*right + 305*right + 3624)/1000;
		if(reverseDrive == 1)
		{
			motor[frontLeft] = motor[backLeft]   = ((int) left) * -1 * sign(vexRT[Ch3]);
			motor[frontRight] = motor[backRight] = ((int) right) * -1 * sign(vexRT[Ch2]);
		}
		else
		{
			motor[frontLeft] = motor[backLeft]   = ((int) left) * 1 * sign(vexRT[Ch3]);
			motor[frontRight] = motor[backRight] = ((int) right) * 1 * sign(vexRT[Ch2]);
		}
		if(vexRT[Btn8L])
		{
			while(vexRT[Btn8L]) { wait1Msec(20); }
			reverseDrive = toggle(reverseDrive);
		}

		if(vexRT[Btn7D])
		{
			mgGoal = 0;
		}
		else if(vexRT[Btn8D])
		{
			mgGoal = 1;
		}
		mobileGoalChange(mgGoal);
	}


}
