#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    PEStatus,       sensorAnalog)
#pragma config(Sensor, in3,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  liftlimit,      sensorTouch)
#pragma config(Sensor, dgtl10, powerALED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, powerBLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, powerCLED,      sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           doubleLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mobileGoal,    tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port6,           chainbar,      tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port7,           doubleRight,   tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port8,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           backLeft,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#define sign(x) (x < 0 ? -1 : 1)
#define toggle(x) (1 - x)
#include "Vex_Competition_Includes.c"
#include "zSmartMotorLib.c"
#include "zBCIPIDLib.c"
#include "zAutonomousFunctions.c"
#include "zAutonomousRoutines.c"

int RUNTEST = 0, TEST = 0; // Manual Autonomous Test Controls
void pre_auton()
{
	SmartMotorsInit();
	SmartMotorPtcMonitorEnable();
	SmartMotorLinkMotors(frontLeft, backLeft);
	SmartMotorLinkMotors(frontRight, backRight);
	SmartMotorLinkMotors(doubleRight, doubleLeft);
	SmartMotorsAddPowerExtender(mobileGoal); // Place Correct Motors
	SmartMotorSetPowerExpanderStatusPort(PEStatus);
	SmartMotorSetControllerStatusLed( SMLIB_CORTEX_PORT_0, powerALED);
	SmartMotorSetControllerStatusLed( SMLIB_CORTEX_PORT_1, powerBLED);
	SmartMotorSetControllerStatusLed( SMLIB_PWREXP_PORT_0, powerCLED);
	bStopTasksBetweenModes = true;
	if(!RUNTEST)
		LcdAutonomousSelection();
}


task autonomous()
{
	SmartMotorRun();
	if(RUNTEST == 1 && TEST == 0)
		testDegmove();
	if(RUNTEST == 1 && TEST == 1)
		testSmallGyroturn();
	if(RUNTEST == 1 && TEST == 2)
		testLargeGyroturn();
}

task usercontrol()
{
	startTask(WATCHDOG);
	startTask(autoStacker);
	SmartMotorRun();

	int left = 0, right = 0, reverseDrive = 0;
	int lastManualMobileGoal = 0;
	int lastManualLift = 0;
	int lastManualClaw = 0;
	while (true)
	{
		// Drive Code
		left  = abs(vexRT[Ch3]);
		right  = abs(vexRT[Ch2]);
		left = (5*left*left + 305*left + 3624)/1000;
		right = (5*right*right + 305*right + 3624)/1000;
		if(reverseDrive == 1)
		{
			motor[frontLeft] = motor[backLeft]   = ((int) left) * reverseDrive * sign(vexRT[Ch3]);
			motor[frontRight] = motor[backRight] = ((int) right) * reverseDrive * sign(vexRT[Ch2]);
		}
		else
		{
			motor[frontLeft] = motor[backLeft]   = ((int) right) * reverseDrive * sign(vexRT[Ch2]);
			motor[frontRight] = motor[backRight] = ((int) left) * reverseDrive * sign(vexRT[Ch3]);
		}
		if(vexRT[Btn8L])
		{
			while(vexRT[Btn8L]) { wait1Msec(20); }
			reverseDrive = toggle(reverseDrive);
		}

		// Mobile Goal
		if(vexRT[Btn5DXmtr2] || vexRT[Btn5UXmtr2])
		{
			mobilePIDActive = 0;
			lastManualMobileGoal = 1;
			SetMotor(mobileGoal, 127);
		}
		else if(vexRT[Btn6DXmtr2] || vexRT[Btn6UXmtr2])
		{
			mobilePIDActive = 0;
			lastManualMobileGoal = 1;
			SetMotor(mobileGoal, -127);
		}
		else if(mobilePIDActive == 0 && lastManualMobileGoal == 1)
		{
			mobilePIDActive = 1;
			mobileGoalSetpoint = nMotorEncoder[mobileGoal];
		}
		else if(vexRT[Btn7D])
		{
			mobilePIDActive = 1;
			mobileGoalSetpoint = mobileGoalDown;
		}
		else if(vexRT[Btn8D])
		{
			mobileGoalSetpoint = mobileGoalUp;
		}

		// Lift (Autostack and Manual)
		if(vexRT[Btn8DXmtr2] || vexRT[Btn8RXmtr2] || vexRT[Btn8LXmtr2] || vexRT[Btn8UXmtr2])
		{
			while(vexRT[Btn8L]) { wait1Msec(20); }
			doubleStackLoader = toggle(doubleStackLoader); // 0 -> 1-0 = 1 ; 1 -> 1-1 = 0 -- Toggle Shorthand
		}
		if(vexRT[Btn7L])
		{
			doublePIDActive = 0;
			SetMotor(doubleLeft, -65);
			SetMotor(doubleRight, -65);
			lastManualLift = 1;
		}
		else if(vexRT[Btn8R])
		{
			doublePIDActive = 0;
			SetMotor(doubleLeft, 65);
			SetMotor(doubleRight, 65);
			lastManualLift = 1;
		}
		else if(doublePIDActive == 0 && lastManualLift == 1)
		{
			doublePIDActive = 1;
			doubleSetpoint = nMotorEncoder[doubleRight];
		}
		else if(vexRT[Btn6U])
		{
			doublePIDActive = 1;
			activateAutoStacker = 1;
		}
		else
		{
			doublePIDActive = 1;
			if(doubleStackLoader)
			{
				doubleSetpoint = doublePreload;
			}
			else
			{
				doubleSetpoint = doubleDown;
			}
		}
		// Claw
		if(vexRT[Btn5D])
		{
			clawPIDActive = 0;
			SetMotor(claw, -127);
			lastManualClaw = 1;
		}
		if(vexRT[Btn6D])
		{
			clawPIDActive = 0;
			SetMotor(claw, 127);
			lastManualClaw = 1;
		}
		else if(lastManualClaw == 1)
		{
			clawPIDActive = 1;
			clawSetpoint = SensorValue[clawPot];
			lastManualClaw = 0;
		}
	}
}
